version: "3.8"

services:
  app:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
      args:
      - VITE_API_URL=http://165.232.129.238:3000
    ports:
      - 80:80
    volumes:
      - ./frontend/src:/app/src
  api:
    build: ./backend
    ports:
      - 3000:3000
    environment:
      DB_URL: mongodb://db/gamify
    volumes:
      - ./backend/app:/app/app
    depends_on:
      - db
  db:
    image: mongo:5.0.26-focal
    ports:
      - 27017:27017
    volumes:
      - gamify:/data/db
volumes:
  gamify: